app/models.py
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

class Quote():

    def __init__(self, author,quoteMsg):
        self.author = author
        self.quoteMsg = quoteMsg

class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    password_hash = db.Column(db.String(255))
    Blogs = db.relationship('Blog', backref = 'user', lazy = 'dynamic')
    Comments=db.relationship('Comment',backref='user',lazy='dynamic')
    @property
    def password(self):
        raise AttributeError("You cannot read the password attribute")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.username}'

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Blog(db.Model):
    __tablename__ =  "blogs"

    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255), index = True)
    subtitle=db.Column(db.String)
    body = db.Column(db.String)
    posted_on = db.Column(db.DateTime, default = datetime.utcnow().strftime('%d %b %Y'))
    Comments = db.relationship('Comment', backref = 'comment', lazy = 'dynamic')
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    def __repr__(self):
        return f'User {self.title}'

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blogs(cls):
        blogs = Blog.query.all()
        return blogs

class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)
    feedback = db.Column(db.String, index = True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    blog_id = db.Column(db.Integer,db.ForeignKey('blogs.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls):
        comments = Comment.query.all()
        return comments

    def __repr__(self):
        return f'User{self.feedback}'

class Subscription(db.Model):

    __tablename__ = 'subscriptions'

    id = db.Column(db.Integer, primary_key = True)
    email= db.Column(db.String(255), unique = True, index = True)

    def __repr__(self):
        return f'User{self.email}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required, Email

class CreateBlog(FlaskForm):
    title = StringField('Blog Title', validators=[Required()])
    subtitle=StringField('Subtitle',validators=[Required()])
    body = TextAreaField('Blog',validators=[Required()])
    submit= SubmitField('Add Blog')

class AddComment(FlaskForm):
    comment = StringField('Comment', validators=[Required()])
    submit = SubmitField('Add Comment')

class EditBlog(FlaskForm):
    body = TextAreaField('Blog',validators=[Required()])
    submit= SubmitField('Edit Blog')

class SubscribeForm(FlaskForm):
    email = StringField('Your Email Address',validators=[Required(),Email()])
    submit= SubmitField('Subscribe')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()
simple = SimpleMDE()


def create_app(config_name):

    app = Flask(__name__)
    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    mail.init_app(app)
    simple.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template, request, redirect, url_for, flash
from . import main
from app import db
from ..requests import get_quotes
from flask_login import login_required, current_user
from .forms import CreateBlog, AddComment, EditBlog, SubscribeForm
from ..models import User, Blog, Comment,Subscription
@main.route('/', methods=['GET', 'POST'])
def index():
    new_quote = get_quotes()
    blogs = Blog.query.all()
    users = User.query.all()
    form = SubscribeForm()
    if form.validate_on_submit():
        email = form.email.data
        subscription = Subscription(email=email)
        db.session.add(subscription)
        db.session.commit()
        return render_template('index.html', new_quote=new_quote, blogs=blogs, users=users, subscribe_form=form)
    return render_template('index.html', new_quote=new_quote, blogs=blogs, users=users, subscribe_form=form)


@main.route('/blog/<id>', methods=["get", "post"])
def blog(id):
    comment_form = AddComment()
    blog = Blog.query.filter_by(id=id).first()
    if comment_form.validate_on_submit():
        feedback = comment_form.comment.data
        comment = Comment(feedback=feedback,
                          user_id=current_user.id, blog_id=id)
        db.session.add(comment)
        db.session.commit()
        comments = Comment.query.filter_by(blog_id=id).all()
        return render_template("blog.html", blog=blog, comments=comments, comment_form=comment_form)
    comments = Comment.query.filter_by(blog_id=id)
    return render_template("blog.html", blog=blog, comment_form=comment_form, comments=comments)


@main.route('/addblog', methods=["get", "post"])
def add_blog():
    blogform = CreateBlog()

    if blogform.validate_on_submit():

        title = blogform.title.data
        subtitle = blogform.subtitle.data
        body = blogform.body.data
        new_blog = Blog(title=title, subtitle=subtitle,
                        body=body, user_id=current_user.id)
        db.session.add(new_blog)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('create_blog.html', blog_form=blogform)


@main.route('/profile/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()
    blogs = Blog.query.filter_by(user_id=user.id).all()
    return render_template("profile/profile.html", user=user, blogs=blogs)


@main.route('/deleteComment/<int:commentid>/<int:blogid>', methods=["get", "post"])
def deleteComment(commentid, blogid):
    comment = Comment.query.filter_by(id=commentid).first()
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("main.blog", id=blogid))


@main.route('/deleteblog/<blogid>', methods=["get", "post"])
def delete_blog(blogid):
    blog = Blog.query.filter_by(id=blogid).first()
    uname = current_user.username
    db.session.delete(blog)
    db.session.commit()
    return redirect(url_for("main.profile", uname=uname))


@main.route('/editblog/<blogid>', methods=["get", "post"])
def edit_blog(blogid):

    form = EditBlog()

    if form.validate_on_submit():
        body = form.body.data
        blog = Blog.query.filter_by(id=blogid).update({"body": body})
        db.session.commit()
        return redirect(url_for("main.profile", uname=current_user.username))
    else:
        form.body.data = Blog.query.filter_by(id=blogid).first().body
    return render_template("update_blog.html", updateblog_form=form)

app/templates/base.html
{%extends 'bootstrap/base.html'%}

{%block styles%}
    {{super()}}
    {{ simplemde.css}}
    {{ simplemde.js }}
    <link href="https://fonts.googleapis.com/css?family=Merriweather|Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Courgette|Merriweather|Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Caveat|Courgette|Merriweather|Satisfy&display=swap" rel="stylesheet">

{% endblock %}

{% block navbar %}
    {% include 'navbar.html'%}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock %}
{% block scripts%}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{%endblock%}

app/templates/blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{%block content%}
    <div class="container-fluid">
        <div class= "row">
            <div class = "col-md-2"></div>
            <div class = "col-md-8">
                <h1>TITLE:  {{ blog.title}}</h1>
                <hr style="border-width: 10px;border-color: lightseagreen;">
                <br>
                <h2>{{blog.subtitle}}</h2>
                <h4>Created by: {{blog.user.username}} on {{blog.posted_on}}</h4>
                <hr>
                <br>
                <p>{{blog.body}}</p>
                <hr style="border-width: 5px;border-color: lightseagreen;">
                {%if current_user.is_authenticated%}
                <div class=" panel comment_form">
                        {{ wtf.quick_form(comment_form) }}
                </div>
                {%endif%}
                <hr style="border-width: 5px;border-color: lightseagreen; ">
                <div>
                    <h1>Comments</h1>
                    {% for comment in comments %}
                    <div style="border:10px solid lightseagreen; padding:20px; border-radius: 20px; margin-top: 5px;">
                            <p>{{comment.feedback}}</p>
                            <p>-by<strong>{{comment.user.username}}</strong></p>
                            {%if current_user.is_authenticated and current_user.id == blog.user_id%}
                            <button><a href="{{url_for('main.deleteComment',commentid=comment.id, blogid=blog.id)}}">Delete</a></button>
                            {%endif%}
                    </div>

                    {%endfor%}
                </div>

            </div>
            <div class = "col-md-2"></div>
        </div>
    </div>
{%endblock%}

app/templates/create_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container-fluid">
        <div class= "row">
            <div class="col-md-2"></div>
            <div class="col-md-8 ">
               <div style="padding:5px;">
                    <h2 style="font-size: 40px;">Add a new blog:</h2> 
                </div>
               <div class="block"> {{ wtf.quick_form(blog_form) }}</div> 
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{%endblock%}

app/templates/index.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock %}

{% block content %}
    <div class="container-fluid" id="cov">
        <div class = "row">
            <div class = "col-md-1"></div>
            <div class = "col-md-6 ">
                <br>
                <h1 style="text-align: center;">Welcome to MY BLOG!!!</h1>
                <h2 style="text-align: center;">Read blogs and create your own if desired</h2>

                <hr style="border-width: 5px ;border-color: lightseagreen;">
                <ul class="blogsColumn" style="margin-left:20px;">
                {% if blogs%}
                    {% for blog in blogs %}
                    <li>
                        <a href="{{url_for('main.blog', id=blog.id)}}"><h1>{{blog.title}}</h1></a>
                        <h3>{{blog.subtitle}}</h3>
                        <h4>Created by <strong>{{ blog.user.username }}</strong> on {{blog.posted_on}}</h4>
                    </li>
                    <hr  style="border-width:2px; size:20px; border-color:lightseagreen; width: 40%; margin-left:0%">
                    {% endfor %}
                {% endif%}
                </ul>
            </div>
            <div class = "col-md-1"></div>
            <div class="col-md-3">
                <div class="panel panel-default subscription">
                    <div>{{ wtf.quick_form(subscribe_form) }}</div>
                </div>
                <div class="quote">
                        <p id="quote">"{{new_quote.quoteMsg}}"</p>
                        <p id="quote">-by <strong>"{{new_quote.author}}"</strong></p>
                        <br>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/navbar.html
    <div class="navbar" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{url_for('main.index')}}"> MY BLOG </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a class="python" href="{{url_for('main.index')}}">Home</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated %}
                        <li><a href="{{url_for('main.add_blog')}}">Create Blog</a></li>
                        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                        <li><a href="{{url_for('auth.logout')}}">LOGOUT</a></li>
                        {% else %}
                        <li><a href="{{url_for('auth.login')}}">LOGIN</a></li>
                        {%endif%}
                    </ul>
                </div>

            </div>
    </div>

app/templates/profile/profile.html
{%extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{%block content%}
<div class="container-fluid">
    <div class="row">


        <div class= "col-md-2"></div>
        <div class= "col-md-8 profile">
                <h2 style="font-size:40px; background-color: lightseagreen; padding:20px; "> Welcome {{user.username| capitalize}} </h2>
                <h3>Following are your added blogs. You can edit them or delete them</h3>
            {%for blog in blogs%}
            <h1>TITLE:  {{ blog.title}}</h1>
            <hr style="border-width: 10px;border-color: grey;">

            <h2>{{blog.subtitle}}</h2>
            <h4>Created by: {{blog.user.username}} on {{blog.posted_on}}</h4>
            <hr>

            <p>{{blog.body}}</p>
            <button class="btn info-btn"><a href="{{url_for('main.delete_blog',blogid=blog.id)}}">DELETE</a></button>
            <button class="btn info-btn"><a href="{{url_for('main.edit_blog', blogid=blog.id)}}">EDIT</a></button>
            <hr style="border-width: 5px;border-color: lightblue;">
            <br>
            {%endfor%}
        </div>
        <div class= "col-md-2"></div>




    </div>
</div>
{%endblock%}

app/templates/update_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container-fluid">
        <div class= "row">
            <div class="col-md-2"></div>
            <div class="col-md-8 ">
               <div style="padding:5px;">
                    <h2 style="font-size: 40px;">Add a new blog:</h2> 
                </div>
               <div class="block"> {{ wtf.quick_form(updateblog_form) }}</div> 
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{%endblock%}